FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD NiveshBharat.jar /opt/NiveshBharat/
EXPOSE 8080
WORKDIR /opt/NiveshBharat/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "NiveshBharat.jar"]
